build:
  environment:
    node:
      version: 24
  dependencies:
    override:
      - npm ci

filter:
  excluded_paths:
    - node_modules/*
    - .next/*
    - coverage/*
    - tests/e2e/*
    - tests/integration/*
    - scripts/*
    - prisma/generated/*

tools:
  external_code_coverage:
    timeout: 600
