build:
  environment:
    node:
      version: 18
  dependencies:
    override:
      - npm ci
  tests:
    override:
      - npm test
  nodes:
    analysis:
      tests:
        override:
          - npm run lint
          - npm run format:check

filter:
  excluded_paths:
    - node_modules/*
    - .next/*
    - coverage/*
    - tests/e2e/*
    - tests/integration/*
    - scripts/*
    - prisma/generated/*

tools:
  external_code_coverage:
    timeout: 600
