build:
  environment:
    node:
      version: latest
    variables:
      NODE_ENV: test
      DATABASE_URL: 'file:./test.db'
      NEXTAUTH_URL: 'http://localhost:3000'
      NEXTAUTH_SECRET: 'test-secret-key'
      GOOGLE_CLIENT_ID: 'test-client-id'
      GOOGLE_CLIENT_SECRET: 'test-client-secret'
  dependencies:
    override:
      - npm ci
      - npx prisma generate
  tests:
    override:
      - npm test
  nodes:
    analysis:
      tests:
        override:
          - npm run lint
          - npm run format:check

filter:
  excluded_paths:
    - node_modules/*
    - .next/*
    - coverage/*
    - tests/e2e/*
    - tests/integration/*
    - scripts/*
    - prisma/generated/*

tools:
  external_code_coverage:
    timeout: 600
