name: Security Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * 1' # weekly on Monday

permissions:
  contents: read

concurrency:
  group: audit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm_audit:
    name: Run npm audit (production)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: npm audit (prod only)
        run: npm audit --omit=dev --audit-level=moderate

      - name: npm audit (full, non-blocking)
        run: |
          npm audit || echo "Dev audit found issues (non-blocking)."


