name: CI

permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: |
          npm run lint || echo "Lint had warnings/errors (non-blocking)"

      - name: Type-check and build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build

      - name: Run Jest tests (with coverage)
        env:
          CI: 'true'
        run: npm run test:coverage

      - name: Run translation checks
        run: npm run test:translations

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

  # Docker smoke test is maintained as a separate workflow in .github/workflows/docker.yml


